#!/bin/bash

# Prepare the bundle config if BUNDLE_PATH is provided in order to avoid
# inconsistencies with how the bundler path is used
if ! [ -z "${BUNDLE_PATH}" ]; then
  mkdir -p .bundle
  cat > ".bundle/config" <<- EOF
---
BUNDLE_PATH: '${BUNDLE_PATH}'
  EOF
fi

exec "$@"
